alias memory='ps -eo cmd,rss,%cpu --sort=-rss | g'
alias g='grep --color=auto'
alias ls='ls -l --color=auto'
alias c='clear'
alias h='history'
alias :q='exit'
alias search='find * -type f | fzf -m'
alias df='df -h'
alias ..='cd ..'
alias cd..='cd ..'
alias mkdir='mkdir -pv'
alias su='sudo -i'
alias class='xprop WM_CLASS'
alias mirrors='sudo reflector --verbose --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist'
