--no-keepaspect-window
--hwdec=auto
--audio-file-auto=all
--audio-channels=stereo
--volume=70
--sub-auto=fuzzy
--osd-font=Noto Sans
--metadata-codepage=auto
save-position-on-quit
ytdl-format=bestvideo[height<=?1080][vcodec^=avc1]+bestaudio/best
