#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config window_gap   0

bspc config focused_border_color "#4B7093"
bspc config normal_border_color  "#212132"

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config single_monocle        true

bspc rule -a firefox         desktop='^1' follow=on
bspc rule -a "XTerm:ranger"  desktop='^2' follow=on
bspc rule -a Quodlibet       desktop='^3' follow=on
bspc rule -a mpv             desktop='^4' follow=on state=fullscreen
bspc rule -a Geany           desktop='^5' follow=on
bspc rule -a "XTerm:xterm"   desktop='^6' follow=on
bspc rule -a Gimp            desktop='^7' follow=on
bspc rule -a Picard          desktop='^8' follow=on
bspc rule -a Steam           desktop='^9' state=floating
bspc rule -a feh             state=floating

setxkbmap -model pc102 -layout us,ru -option grp:alt_shift_toggle &
xsetroot -cursor_name left_ptr &
feh --bg-scale /home/sergey/Pictures/zamok.jpg &
killall -q picom; picom &
$HOME/.config/polybar/launch.sh
