#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config automatic_scheme spiral
bspc config initial_polarity first_child

bspc config border_width 2
bspc config window_gap   0

bspc config focused_border_color "#4B7093"
bspc config normal_border_color  "#23252e"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config single_monocle        true

bspc rule -a firefox   desktop='^1' follow=on
bspc rule -a files     desktop='^2' follow=on
bspc rule -a Quodlibet desktop='^3' follow=on
bspc rule -a Audacity  desktop='^3' follow=on
bspc rule -a terminal  desktop='^4' follow=on
bspc rule -a editor    desktop='^5' follow=on
bspc rule -a mpv       desktop='^6' follow=on
bspc rule -a Gimp-2.10 desktop='^7' follow=on
bspc rule -a Picard    desktop='^8' follow=on
bspc rule -a Steam     desktop='^9' follow=on

bspc rule -a Blueman-manager state=floating
bspc rule -a Steam           state=floating
bspc rule -a XCalc           state=floating
bspc rule -a calendar        state=floating

xsetroot -cursor_name left_ptr &
feh --bg-scale /home/sergey/Pictures/oz.jpg &
$HOME/.config/polybar/bspwm.sh
