;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #212132
background-alt = #2A2A44
foreground = #E5E5E5
primary = #E79B42
secondary = #8ABEB7
alert = #E84C4C
disabled = #333333
xwork = #FFA500
xwind = #AAC9F1
vol = #CDDC45
ram = #FE75F4
cpu = #7DD0F5
temp = #F5628A
date = #FDB75F
keyboard = #F57CB8
bat = #8DF08D
sep = #919191

[bar/example]
width = 100%
height = 24pt
; radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

; border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.sep}

font-0 = JetBrains Mono:style=Regular:size=10;2
font-1 = Font Awesome 6 Brands Regular:style=Regular:size=10;2
font-2 = Font Awesome 6 Free Solid:style=Solid:size=10;2
font-3 = Font Awesome 6 Free Regular:style=Regular:size=10;2

modules-left = xworkspaces xwindow
modules-center = date
modules-right = pulseaudio memory cpu temperature battery xkeyboard

cursor-click = pointer
; cursor-scroll = ns-resize

enable-ipc = true

tray-position = right

; wm-restack = generic
wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-foreground = ${colors.primary}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-background = ${colors.background}
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.xwind}
format-padding = 1
label = %title%
label-maxlen = 50
label-empty = Empty
label-empty-foreground = #707880

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume =  %percentage%%
label-volume-foreground = ${colors.vol}
label-muted = muted
label-muted-foreground = ${colors.alert}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.keyboard}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
label =  %percentage_used:2%%
label-foreground = ${colors.ram}

[module/cpu]
type = internal/cpu
interval = 2
label =  %percentage:2%%
label-foreground = ${colors.cpu}

[module/temperature]
type = internal/temperature
interval = 5
thermal-zone = 0
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
label =  %temperature-c%
label-foreground = ${colors.temp}

[module/battery]
type = internal/battery
full-at = 99
low-at = 5
battery = BAT0
adapter = ADP0
poll-interval = 5
label-full =  %percentage%%
label-charging =  %percentage%%
label-discharging =  %percentage%%
label-full-foreground = ${colors.bat}
label-charging-foreground = ${colors.bat}
label-discharging-foreground = ${colors.bat}

[module/date]
type = internal/date
interval = 1
date =  %a %d   %H:%M:%S
label = %date%
label-foreground = ${colors.date}

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
