theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "file-modification-indicator",
  "read-only-indicator",
]
# center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-z = 'no_op'
C-r = 'redo'

[keys.select]
C-z = 'no_op'
