[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[language-server.taplo]
config = {}


[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = [
  "py",
  "pyi",
  "py3",
  "pyw",
  "ptl",
  "rpy",
  "cpy",
  "ipy",
  "pyt",
  { glob = ".python_history" },
  { glob = ".pythonstartup" },
  { glob = ".pythonrc" },
  { glob = "SConstruct" },
  { glob = "SConscript" },
]
shebangs = ["python"]
roots = [
  "pyproject.toml",
  "setup.py",
  "poetry.lock",
  "pyrightconfig.json",
  "requirements.txt",
  ".venv/",
]
comment-token = "#"
language-servers = [
  { name = "pyright", except-features = [
    "diagnostics",
  ] },
  "ruff",
]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "bash", args = [
  "-c",
  "ruff format --line-length 120 -q . && black --line-length 120 -q -",
] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"]

[language-server.pyright.config]
python.analysis.venvPath = "."
python.analysis.venv = ".venv"
python.analysis.lint = true
python.analysis.inlayHint.enable = true
python.analysis.autoSearchPaths = true
python.analysis.diagnosticMode = "workspace"
python.analysis.useLibraryCodeForType = true
python.analysis.logLevel = "Error"
python.analysis.typeCheckingMode = "off"
python.analysis.autoImoprtCompletion = true
python.analysis.reportOptionalSubscript = false
python.analysis.reportOptionalMemberAccess = false

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true


[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true
