[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[language-server.taplo]
config = {}


[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]


[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true


[[language]]
name = "haskell"
auto-format = true


[[language]]
name = "bash"
auto-format = true
